name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing lexorrr.com server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 139.162.60.123
          username: root
          key: ${{ secrets.REACT_ACTIONS_SECRET }}
          port: 22
          script: |
            cd react-test-github-actions
            git pull origin main
            git status
