name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing lexorrr.com server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 139.162.60.123
          username: root
          passphrase: fatbox123$$
          key: ${{ secrets.REACT_ACTIONS_SECRET }}
          port: 22
          script: |
            cd react-test-github-actions
            git pull origin main
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm install
            npm run build
            cp -r dist/ /root/deploy/
